/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.semconv.incubating;

import static io.opentelemetry.api.common.AttributeKey.stringKey;

import io.opentelemetry.api.common.AttributeKey;

// DO NOT EDIT, this is an Auto-generated file from
// buildscripts/templates/registry/incubating_java/IncubatingSemanticAttributes.java.j2
@SuppressWarnings("unused")
public final class AzIncubatingAttributes {

  /**
   * The unique identifier of the service request. It's generated by the Azure service and returned
   * with the response.
   */
  public static final AttributeKey<String> AZ_SERVICE_REQUEST_ID =
      stringKey("az.service_request_id");

  private AzIncubatingAttributes() {}
}
