/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.semconv.incubating;

import static io.opentelemetry.api.common.AttributeKey.booleanKey;
import static io.opentelemetry.api.common.AttributeKey.stringArrayKey;
import static io.opentelemetry.api.common.AttributeKey.stringKey;

import io.opentelemetry.api.common.AttributeKey;
import java.util.List;

// DO NOT EDIT, this is an Auto-generated file from
// buildscripts/templates/registry/incubating_java/IncubatingSemanticAttributes.java.j2
@SuppressWarnings("unused")
public final class PprofIncubatingAttributes {
  /**
   * Provides an indication that multiple symbols map to this location's address, for example due to
   * identical code folding by the linker. In that case the line information represents one of the
   * multiple symbols. This field must be recomputed when the symbolization state of the profile
   * changes.
   */
  public static final AttributeKey<Boolean> PPROF_LOCATION_IS_FOLDED =
      booleanKey("pprof.location.is_folded");

  /** Indicates that there are filenames related to this mapping. */
  public static final AttributeKey<Boolean> PPROF_MAPPING_HAS_FILENAMES =
      booleanKey("pprof.mapping.has_filenames");

  /** Indicates that there are functions related to this mapping. */
  public static final AttributeKey<Boolean> PPROF_MAPPING_HAS_FUNCTIONS =
      booleanKey("pprof.mapping.has_functions");

  /** Indicates that there are inline frames related to this mapping. */
  public static final AttributeKey<Boolean> PPROF_MAPPING_HAS_INLINE_FRAMES =
      booleanKey("pprof.mapping.has_inline_frames");

  /** Indicates that there are line numbers related to this mapping. */
  public static final AttributeKey<Boolean> PPROF_MAPPING_HAS_LINE_NUMBERS =
      booleanKey("pprof.mapping.has_line_numbers");

  /**
   * Free-form text associated with the profile. This field should not be used to store any
   * machine-readable information, it is only for human-friendly content.
   */
  public static final AttributeKey<List<String>> PPROF_PROFILE_COMMENT =
      stringArrayKey("pprof.profile.comment");

  /**
   * Documentation link for this profile type.
   *
   * <p>Notes:
   *
   * <p>The URL must be absolute and may be missing if the profile was generated by code that did
   * not supply a link
   */
  public static final AttributeKey<String> PPROF_PROFILE_DOC_URL =
      stringKey("pprof.profile.doc_url");

  /**
   * Frames with Function.function_name fully matching the regexp will be dropped from the samples,
   * along with their successors.
   */
  public static final AttributeKey<String> PPROF_PROFILE_DROP_FRAMES =
      stringKey("pprof.profile.drop_frames");

  /**
   * Frames with Function.function_name fully matching the regexp will be kept, even if it matches
   * drop_frames.
   */
  public static final AttributeKey<String> PPROF_PROFILE_KEEP_FRAMES =
      stringKey("pprof.profile.keep_frames");

  /**
   * Records the pprof's default_sample_type in the original profile. Not set if the default sample
   * type was missing.
   *
   * <p>Notes:
   *
   * <p>This attribute, if present, MUST be set at the scope level
   * (resource_profiles[].scope_profiles[].scope.attributes[]).
   */
  public static final AttributeKey<String> PPROF_SCOPE_DEFAULT_SAMPLE_TYPE =
      stringKey("pprof.scope.default_sample_type");

  /**
   * Records the indexes of the sample types in the original profile.
   *
   * <p>Notes:
   *
   * <p>This attribute, if present, MUST be set at the scope level
   * (resource_profiles[].scope_profiles[].scope.attributes[]).
   */
  public static final AttributeKey<List<Long>> PPROF_SCOPE_SAMPLE_TYPE_ORDER =
      longArrayKey("pprof.scope.sample_type_order");

  // Enum definitions

  private PprofIncubatingAttributes() {}
}
