name: Build Pull Request

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    with:
      cache-read-only: true
    secrets:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

  link-check:
    uses: ./.github/workflows/reusable-link-check.yml

  required-status-check:
    if: always()
    needs:
      - common
      - link-check # wait for link check to complete, but don't require it to pass for merging
    runs-on: ubuntu-latest
    steps:
      # The reusable workflow success depends on all its jobs passing
      - if: needs.common.result != 'success'
        run: exit 1 # fail
